// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyAXggmLSFzdHLzQDmpKA7_mQi-O02MKnVY',
  //   appId: '1:254290848350:web:5a7ba4691ab06dde07e2cf',
  //   messagingSenderId: '254290848350',
  //   projectId: 'mychat-981ad',
  //   authDomain: 'mychat-981ad.firebaseapp.com',
  //   storageBucket: 'mychat-981ad.appspot.com',
  //   measurementId: 'G-YWTZZ678BZ',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLsjRRwOaZN9jE1ZR4P3JN7Q4SjRYcmo',
    appId: '1:254290848350:android:8e9246cf6ad03cff07e2cf',
    messagingSenderId: '254290848350',
    projectId: 'mychat-981ad',
    storageBucket: 'mychat-981ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZp8hML0ldEwclJ8C5Hnoi-UxsbjtrXu4',
    appId: '1:254290848350:ios:1a148dbb910246fd07e2cf',
    messagingSenderId: '254290848350',
    projectId: 'mychat-981ad',
    storageBucket: 'mychat-981ad.appspot.com',
    androidClientId:
        '254290848350-fgn7fnqiq42a1mmno3hndunc054r9qc0.apps.googleusercontent.com',
    iosClientId:
        '254290848350-3fd6k8il7qkavnesm1pf4j30ef7564oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDZp8hML0ldEwclJ8C5Hnoi-UxsbjtrXu4',
  //   appId: '1:254290848350:ios:1a148dbb910246fd07e2cf',
  //   messagingSenderId: '254290848350',
  //   projectId: 'mychat-981ad',
  //   storageBucket: 'mychat-981ad.appspot.com',
  //   iosBundleId: 'com.example.chatApp',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyAXggmLSFzdHLzQDmpKA7_mQi-O02MKnVY',
  //   appId: '1:254290848350:web:600427bcc832c28307e2cf',
  //   messagingSenderId: '254290848350',
  //   projectId: 'mychat-981ad',
  //   authDomain: 'mychat-981ad.firebaseapp.com',
  //   storageBucket: 'mychat-981ad.appspot.com',
  //   measurementId: 'G-4E0J4X5NV0',
  // );
}
